<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>dd5ac116-47f2-4209-94cb-be511b6fb0ba</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Amazon.Extensions.Configuration.SystemsManager" Version="7.1.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="src\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Sharply.Application\Sharply.Application.csproj" />
	  <ProjectReference Include="..\Sharply.Domain\Sharply.Domain.csproj" />
	  <ProjectReference Include="..\Sharply.Infrastructure\Sharply.Infrastructure.csproj" />
	</ItemGroup>

</Project>